# Generated by Django 5.0.6 on 2024-07-05 02:37

import Book.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to=Book.helpers.SaveMedia.save_book_image_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to=Book.helpers.SaveMedia.save_book_image_path),
        ),
    ]
